### ISSUE TITLE
Heroku is rejecting this buildpack

### ISSUE THREAD

**Issue by mabodo** [sethfitz/heroku-buildpack-pgsql#2]
I've been using this buildpack for quite month's with no problem. Today I got an error when pushing. (Today moring was already working)

The traceback I'm getting is this one:

```
=====> Downloading Buildpack: https://github.com/mojodna/heroku-buildpack-pgsql
=====> Detected git submodules. Initializing...
Cloning into 'stack-images'...
/tmp/buildpack_56e3673bb4bb3d6edf0dd31a423886e2/bin/compile: line 36: Submodule: command not found

 !     Push rejected, failed to compile Multipack app

To git@heroku.com:social-database-manager.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:social-database-manager.git'
```

For me the problem seems to be heritated from stack-images. If I found the problem I let you know.

DAVID

**Comment by sethfitz** [comment]
What's your `BUILDPACK_URL`?  I'm wondering which is responsible for checking out the submodules (which really don't need to be in there anyway except for build purposes, so thanks for the heads-up!).

**Comment by mabodo** [comment]
I'm using the multipack https://github.com/ddollar/heroku-buildpack-multi.git
In fact I see It's been recently updated (11h ago) with a commit about the submodels.
I'll try an old version of that! (Thanks for the quick response!)

**Comment by mabodo** [comment]
I changed the `BUILDPACK_URL` to a previous multipack commit 'https://github.com/ddollar/heroku-buildpack-multi.git#6e79094381a1773b9a' This way it allows me to push.
Thanks!

**Comment by sethfitz** [comment]
Sweet.  I'm going to spend some time later today figuring out how to deal with those changes.

**Comment by sethfitz** [comment]
Should be fixed in https://github.com/ddollar/heroku-buildpack-multi/commit/331b0277c8b091fb3580a543e18ad5f1fe4532f5.

Can you unpin multipack and try it again?

**Comment by mabodo** [comment]
Yep is working! Unpined multipack allows the push!
